server:
  port: 8001
spring:
  application:
    name: blog-articles
  cloud:
    nacos:
      server-addr: 192.168.1.10:8848
  datasource:
    data-username: gy_blog
    data-password: guyue112
    url: jdbc:mysql://192.168.1.10:3306/blog
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  typeAliasesPackage: com.guyue.entity
  mapperLocations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true #采用驼峰标识