version: "3.9"
networks:
  blog_network:
services:
  nacos:
    image: nacos/nacos-server
    ports:
      - "8848:8848"
    environment:
      - "JVM_XMS=256m"
      - "JVM_XMX=256m"
      - "MODE=standalone"
    networks:
      - blog_network